# Copyright (c) 2025 Zensical and contributors

# SPDX-License-Identifier: MIT
# Third-party contributions licensed under DCO

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

name: Download ctrl-z binary
description: Download and unpack the ctrl-z binary for CI
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -e
        ASSET="ctrl-z-x86_64-unknown-linux-gnu.tar.gz"
        VERSION=$(curl -s https://api.github.com/repos/squidfunk/ctrl-z/releases/latest | jq -r .tag_name)
        curl -sSL "https://github.com/squidfunk/ctrl-z/releases/download/${VERSION}/${ASSET}" -o ctrl-z.tar.gz
        tar -xzf ctrl-z.tar.gz
        chmod +x ctrl-z
        echo "$PWD" >> $GITHUB_PATH
